# .travis.yml for continuous build/test
#
# Using standard travis R build env now
# from here: https://docs.travis-ci.com/user/languages/r/

language: r
cache: packages
sudo: true

repos:
  CRAN: https://cran.rstudio.com
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev

warnings_are_errors: false

r_packages:
  - covr


after_success:
  - Rscript -e 'covr::coveralls()'

r:
  - release

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --as-cran


notifications:
  email:
    on_success: change
    on_failure: change